[Design] 더미 데이터를 밴드 정보 View에 연결했습니다.
DeveloperAcademy-POSTECH/MacC-GetARock pull request #109
Opened 2022-11-24 03:18 UTC by unuhqueen

## 관련 이슈
- close #91 

## 배경
#76 에서 생성된 더미 데이터를 밴드 정보 View에 연결합니다.

## 작업 내용
- 더미데이터를 밴드 정보 View의 `Label`들과 연결했습니다.
- 그 외 `Stack View`의 distribution 수정, `View` 이름 변경, Scroll 기능 수정 등 잡다한 Storyboard 설정을 수정했습니다.

## 테스트 방법
- StoryBoard 형태라서 제 브랜치로 checkout한 다음에 리뷰해주시면 감사하겠습니다.
- `plist` 파일의 `Storyboard Name`을 `BandInfo`로 변경하면 빌드 시에 확인할 수 있습니다.

## 리뷰 노트
더미 데이터를 연결하는 함수를 구현할 때 대부분 for문을 사용했는데 적절한지 궁금합니다.

## 스크린샷

<img width="300" alt="" src="https://user-images.githubusercontent.com/49133245/203686456-cc9373cd-bfc2-4291-ac43-9c926f241ee4.png">

2022-11-24 03:27 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2022-11-24 03:29 UTC, unuhqueen commented
앞의 PR(#87)이랑 연동된 브랜치라서 PR이 닫히고 나서 리뷰하는게 편하실 듯 합니다 😅

2022-11-29 00:12 UTC, manju-minji commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
>          bandIntroduceView.layer.borderColor = UIColor.dividerBlue.cgColor
RepertoireTableViewCell에서도 UIView 속성과 관련하여 유사한 코드가 보이는데,
반복되는 곳이 많다면 UIView의 extension을 이용해서

bandIntroduceView.apply머시기 이런식으로 할 수 있지 않을까 싶네요!!

2022-11-29 00:14 UTC, manju-minji commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +        return sum
여기선 for 문 말고 reduce를 활용해보는게 어떨까요?

2022-11-29 00:14 UTC, manju-minji commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +        return positionNameArray
여기선 map을 활용해보는게 어떨까요?

2022-11-29 00:14 UTC, manju-minji commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +        return numberOfPositionArray
여기도 map을 활용 할 수 있지 않을까 싶네요

2022-11-29 00:14 UTC, manju-minji commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +        return bandAgeArray
여기도!

2022-11-30 01:03 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2022-12-01 02:46 UTC, unuhqueen commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
>          bandIntroduceView.layer.borderColor = UIColor.dividerBlue.cgColor
e2fdabceff5717dd1c25dc383ec13fb1045862a4 반영했습니다!

2022-12-01 02:53 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2022-12-01 02:53 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2022-12-01 09:01 UTC, compuTasha commented on GetARock/GetARock/Global/Supports/Info.plist
> +					<string>BandInfo</string>
p1;

이것.. 원래대로 돌려주세욧..!

2022-12-01 13:49 UTC, unuhqueen commented on GetARock/GetARock/Global/Supports/Info.plist
> +					<string>BandInfo</string>
f59fc4d71d4f4b8b0aded405db1a1c0767b3e29e 아앗 이런 실수를 하다니,, 바로 반영했습니다!!

2022-12-01 13:56 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2022-12-01 13:57 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2022-12-01 15:21 UTC, skycat0212 commented on GetARock/GetARock/Global/Extension/UIView+Extension.swift
> +    }
p2;
bgColor 축약어 사용지양해주세요 + 만약 축약어를 쓴다면 BGColor / bgColor 가 되어야 할 것 같아요
bgColor, Radius, border를 어떻게 세팅하는지도 나타내지 않고 applyBgcolorRadiusBorder와 같은 네이밍을 전역적으로 사용하는 건 적절하지 않은 것 같아요. 네이밍을 통해 구체적으로 어떻게 적용시키는 건지 알려주거나, 파라미터를 받아 적용시키는게 어떨까요?

2022-12-01 15:23 UTC, skycat0212 commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +        return positionNameArray
p3;
함수 내부적으로 append 연산이 사용되기는 하지만, 함수의 네이밍이 append 가 되기에는 함수 외적으로 append하는 인터렉션이 없는 것 같아요.

2022-12-01 15:25 UTC, skycat0212 commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +    private func calculateNumberOfBandMemberText() -> Int {
혹시 네이밍에 text는 왜 들어가는 걸까요?? 🤔

2022-12-01 15:26 UTC, skycat0212 commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +    private func appendNumberOfPostionArray() -> [Int] {
p3;
여기도 네이밍 확인해주세요

2022-12-02 02:53 UTC, manju-minji commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +        return positionNameArray
return selectedBand.filledPosition.map{ $0.position.toKorean() }

이런식으로 사용할 수 있지 않을까 싶습니다!

2022-12-02 06:23 UTC, Somin-DS commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +        return bandAgeArray
고차함수 활용에 대해서 같이 공부하고 갑니다!!!!👍

2023-01-03 10:58 UTC, compuTasha commented
@unuhqueen 
시간이 많이 지나서 리마인더 드립니당 확인 부탁드려요! 🫶

2023-01-03 12:54 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2023-01-03 13:05 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2023-01-05 01:55 UTC, unuhqueen commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +        return positionNameArray
9d6a8484bb4528d516729291942521534cc8266a 덕분에 고차함수 엄청 열심히 공부하고 반영했습니다ㅠㅠ

2023-01-05 01:55 UTC, unuhqueen commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +        return numberOfPositionArray
9d6a8484bb4528d516729291942521534cc8266a map 활용했습니다!

2023-01-05 01:56 UTC, unuhqueen commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +        return bandAgeArray
9d6a8484bb4528d516729291942521534cc8266a map 활용했습니다!

2023-01-05 01:56 UTC, unuhqueen commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +        return sum
27b43a220c0adcd8eecb6c6936b71172256f3f54 reduce 반영했습니다!

2023-01-05 02:00 UTC, unuhqueen commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +        return positionNameArray
9d6a8484bb4528d516729291942521534cc8266a map 함수 활용으로 대체되었습니다!

2023-01-05 02:00 UTC, unuhqueen commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +    private func appendBandAgeArray() -> [String] {
9d6a8484bb4528d516729291942521534cc8266a map 함수 활용으로 대체되었습니다!

2023-01-05 02:00 UTC, unuhqueen commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +    private func calculateNumberOfBandMemberText() -> Int {
27b43a220c0adcd8eecb6c6936b71172256f3f54 reduce 함수 활용으로 대체되었습니다!

2023-01-05 02:01 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2023-01-05 02:48 UTC, unuhqueen commented on GetARock/GetARock/Global/Extension/UIView+Extension.swift
> +    }
3c77b3a8c0d843bf92a91054702be4e6a56962c7 함수 네이밍 변경했습니다!

2023-01-05 02:56 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2023-01-05 06:12 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2023-01-06 06:18 UTC, EuniceNam reviewed
고생하셨습니다!
이미지셋이 자꾸 튀어나와서 시작지점만 해당 스토리보드로 바꿔서 빌드하면 강제종료되는 문제가 있습니다. 
데모에서는 그렇지 않았어서, 코드상에서 처리할 수 있는 문제라면 처리 부탁드려요. 
Xcode에서만 있는 문제라면 알려주시면 어프루브 하겠습니다.

2023-01-06 06:18 UTC, EuniceNam commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +            cell.positionImageView.image = UIImage(named: "Etc")!
p4; positionNameLabel.text에 따라서 이미지를 바꾸는 것이 어색해요.

바로 위의 numberOfPositionLabel과 numberOfPositionArray처럼 positionImageNameArray를 만들어서 하면 좋을 것 같아요. 

PlayPosition에 toKorean()처럼 imageName() 함수를 만들어 이미지 이름을 반환하게 하면 뷰컨트롤러의 프로퍼티로 `var positionImageNameArray: [String] = selectedBand.filledPosition.map { $0.position.imageName() }`를 추가하고, 데이터소스에 `cell.positionImageView.image = UIImage(named: self.positionImageNameArray[indexPath.item])`로 추가해서 쓰면 될 것 같아요.

2023-01-06 06:18 UTC, EuniceNam commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
>      private func generateBandAgeLabelText() -> String {
p4; `return bandAgeArray.joined(separator: ", ")` 로 축약될 것 같아요. 
함수 대신 66줄에 `bandAgeLabel.text = bandAgeArray.joined(separator: ", ")` 로 하면 좋을 것 같아요.

2023-01-06 06:18 UTC, EuniceNam commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
p5; 86줄 compositional에 두 번째 i가 빠진 오타가 있습니다

2023-01-06 06:18 UTC, EuniceNam commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
p4; 
// MARK: - Life Cycle이 위에 Property, View와 함께 빠진 것 같아요. 

레이아웃 사이클이 존재한다는 걸 배워가요:)
(updateViewConstraints, viewWillLayoutSubviews, 저처럼 처음 보신다면 [참고 블로그](https://daeun28.github.io/이론/post22/))

2023-01-06 13:00 UTC, compuTasha commented
커밋에 이슈 넘버가 빠져있어요..!! 뒤에 꼭 붙여주세요!

2023-01-08 08:44 UTC, skycat0212 requested changes
데모 버전에서는 이미지셋이 계속 누락되는 문제를 피하기 위해서, 이미지 파일 이름을 영어로 해서 이미지셋을 다시 세팅했습니다.
이미지 누락 관련해서 계속해서 문제가 생기는 것 같은데 해당 이슈 해결 부탁드립니다.
+) 아무리 이미지셋을 등록했다 하더라도 지금과 같은 문제가 생길 수 있기 때문에 강제 언래핑은 지양하는 게 좋을 것 같습니다.

2023-01-08 08:46 UTC, skycat0212 commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +            cell.positionImageView.image = UIImage(named: "Etc")!
p1;
강제 언래핑으로 앱이 터지고 있어요. UIImage를 세팅하는 방식에 변화가 필요합니다.

2023-01-08 08:48 UTC, skycat0212 commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +            cell.positionImageView.image = UIImage(named: "Etc")!
> positionNameLabel.text에 따라서 이미지를 바꾸는 것이 어색해요.

동의합니다!
이미 만들어진 PlayPosition enum을 활용하는 것도 좋을 것 같아요.
그리고 else if 문을 이렇게 같은 조건을 반복하여 열거해서 사용할 거라면, switch문 사용을 고려해보는 것이 좋을 것 같아요.

2023-01-08 09:08 UTC, skycat0212 commented on GetARock/GetARock/Global/Extension/UIView+Extension.swift
> +    func setUIOfBandIntroduceViewAndRepertoireCellView() {
p3;
네이밍으로 봤을 때, `setUIOfBandIntroduceViewAndRepertoireCellView` 이 메서드가 UIView extension에 있어야 할 메서드 같지는 않은데, 해당 부분을 사용하는 곳에서 정의하는 것은 어떨까요?

2023-01-08 09:12 UTC, skycat0212 commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +    private let selectedBand: Band = MockData.bands[0].band
p3;
selectedBand의 정보를 바탕으로 나머지 정보가 세팅되는 것이기 때문에 selectedBand를 위쪽으로 먼저 선언해주는 것이 가독성 향상에 도움이 될 것 같습니다.

2023-01-09 16:18 UTC, unuhqueen commented on GetARock/GetARock/Global/Extension/UIView+Extension.swift
> +    func setUIOfBandIntroduceViewAndRepertoireCellView() {
3fd3291153f100502bf83c8243421806ba4aa983 함수 네이밍 변경하고 함수 위치는 `BandInfoViewController` 안으로 넣었습니다. 그리고 함수 인자를 하나 추가해서 비슷한 박스 디자인에서 사용할 수 있도록 변경했어요~

2023-01-09 16:19 UTC, unuhqueen commented on GetARock/GetARock/Global/Resource/Assets.xcassets/Bass.imageset/Contents.json
> +      "scale" : "2x"
3fd3291153f100502bf83c8243421806ba4aa983 이거 어케 하는지 몰랐는데 덕분에 새로 깨닫고 반영하구 갑니다,,

2023-01-09 16:19 UTC, unuhqueen commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +            cell.positionImageView.image = UIImage(named: "Etc")!
3fd3291153f100502bf83c8243421806ba4aa983 너무 좋은 팁이네요!! `PlayPosition`에 함수 추가해서 위와 같은 형식으로 반영했습니다!

2023-01-09 16:20 UTC, unuhqueen commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
>      private func generateBandAgeLabelText() -> String {
3fd3291153f100502bf83c8243421806ba4aa983 덕분에 또 새로운 함수를,,, 알고 갑니다,,, 고마어요 유니스,,, 반영했어요!

2023-01-09 16:20 UTC, unuhqueen commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
3fd3291153f100502bf83c8243421806ba4aa983 헉 예리하시다!!! 반영했습니다~

2023-01-09 16:20 UTC, unuhqueen commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
3fd3291153f100502bf83c8243421806ba4aa983 덕분에 mark 주석 다 채워넣었습니다~

2023-01-09 16:22 UTC, unuhqueen commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +            cell.positionImageView.image = UIImage(named: "Etc")!
3fd3291153f100502bf83c8243421806ba4aa983 유니스가 리뷰에 남긴 방식으로 변경하여 반영했습니다!

2023-01-09 16:22 UTC, unuhqueen commented on GetARock/GetARock/Screen/BandInfo/VC/BandInfoViewController.swift
> +    private let selectedBand: Band = MockData.bands[0].band
3fd3291153f100502bf83c8243421806ba4aa983 property 중 맨 위로 올렸습니다!

2023-01-09 16:22 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2023-01-11 08:49 UTC, compuTasha approved these changes
여기 리뷰 보면서 저도 공부합니다.. 
너무 고생하셨어요!! 👍👍

2023-01-11 10:59 UTC, EuniceNam commented on GetARock/GetARock/Global/Extension/UIView+Extension.swift
> +    func setUIOfBandIntroduceViewAndRepertoireCellView() {
* @skycat0212 해당 메서드가 UICollectionViewCell, UITableViewCell, 그리고 뷰컨트롤러 내의 UIView에 각 1회씩 총 3개의 다른 파일에서 쓰여서 UIView Extension도 좋아보이는데 어떤가요?
  * Extension 외에 함수가 정의된 파일 외의 파일에서 쉽게 적용할 방법이 있다면 알려주시면 감사합니다. 
* `BandInfoViewController` 내에 들어가는 함수라면
  * `static` 이 좋을 것 같아요. 
    * **p2**; 뷰컨트롤러 밖의 `BandMemberCollectionViewCell`, `RepertoireTableViewCell`에 적용시킬 때 `BandInfoViewController().함수(view:, cornerRadius:)`로 뷰컨트롤러 인스턴스 만들어서 하는 것이 자원을 불필요하게 사용할 것 같아요. 
  * p4; BandInfo는 함수명에서 빠져도 좋을 것 같아요. `applyBoxDesign()`나`setupBoxAttribute()` 정도 추천해볼게요. (더 좋은 이름이 있을 것 같아요)
  * p4; UIView+Extension.swift 파일의 내용이 없어지므로 파일 삭제해주시면 좋을 것 같아요.

2023-01-11 11:09 UTC, EuniceNam requested changes
고생하셨습니다! 뷰컨트롤러로 옮겨진 함수에 대해 의문이 생겨서ㅠ 수정 요청드립니다. [기존 코멘트](https://github.com/DeveloperAcademy-POSTECH/MacC-GetARock/pull/109#discussion_r1066856549) 관련이라 그쪽에 남겨두었습니다. 확인 부탁드려요. 

+) 이미지 안 빠지고 잘 나와요:)

2023-01-11 13:33 UTC, unuhqueen commented on GetARock/GetARock/Global/Extension/UIView+Extension.swift
> +    func setUIOfBandIntroduceViewAndRepertoireCellView() {
둘 다 좋은 의견이네요! 저도 유니스 의견에 동의하는게 리뷰 과정에서 함수를 살짝 수정하면서 세군데나 쓰이게 돼서 UIView extension도 좋아 보입니다. 스누피 의견도 들어보고 최종적으로 바꿀게요!

2023-01-11 13:52 UTC, skycat0212 commented on GetARock/GetARock/Global/Extension/UIView+Extension.swift
> +    func setUIOfBandIntroduceViewAndRepertoireCellView() {
> @skycat0212 해당 메서드가 UICollectionViewCell, UITableViewCell, 그리고 뷰컨트롤러 내의 UIView에 각 1회씩 총 3개의 다른 파일에서 쓰여서 UIView Extension도 좋아보이는데 어떤가요?

반복적으로 사용된다면 UIView에 구현하는 것도 괜찮은 것 같네요. 좋습니다.

2023-01-11 13:59 UTC, skycat0212 approved these changes
수고하셨습니다!
유니스 리뷰 쪽 마무리되면 merge해도 괜찮을 것 같아요!

2023-01-11 14:45 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2023-01-11 15:05 UTC, EuniceNam approved these changes

2023-01-11 15:14 UTC, unuhqueen commented on GetARock/GetARock/Global/Extension/UIView+Extension.swift
> +    func setUIOfBandIntroduceViewAndRepertoireCellView() {
혹시 `roundedTextBoxWithBorder`은 어떤가요? 이유는.. 피그마를 확인해본 결과 이런 식으로 흰색 border가 있는 텍스트 박스는 다 같은 함수를 적용해도 될 것 같아서... 입니다.. 아아 함수 네이밍 어렵네요 흑흑

2023-01-11 16:02 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2023-01-11 16:05 UTC, merged

2023-01-11 16:35 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |