[Fix] (스누피 데모 팔로업) 모여락 페이지를 데이터와 동적으로 연결시기 위한 작업입니다.
DeveloperAcademy-POSTECH/MacC-GetARock pull request #128
Opened 2023-01-06 02:41 UTC by siro96-01

## 관련 이슈
(#125)
(#126)

## 배경

(#126)번 디스커션에서 다룬 문제를 우선적으로 반영하기 위해서 빠르게 pr 올립니다. 
(#125)번 이슈에서는 현재 @IBOutlet 추가하는 작업만 진행되었습니다.

## 작업 내용

(#126)번 디스커션 해결을 위해서 프로젝트 파일을 새로 만들어서 다시 작업했습니다.

## 테스트 방법

info.plist의 스토리보드 시작점을 GatheringInfoPage로 변경해 주시고 화면이 제대로 실행되는지만 확인해주시면 됩니다..!!

## 리뷰 노트

프로젝트 파일 변경사항이 반영되어야해서 프로젝트 파일도 같이 push 하였습니당.

## 스크린샷
<img width="343" alt="스크린샷 2023-01-06 오전 11 38 51" src="https://user-images.githubusercontent.com/101700487/210918719-32376505-f262-492d-b9d4-79a90993a547.png">

2023-01-06 02:51 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2023-01-06 04:06 UTC, EuniceNam requested changes
고생하셨습니다! 스토리보드 활용법 배워가요. 

p4; PR 레이블에 Feat 빼도 될 것 같고, 담당자 등 레이블 추가하시면 좋을 것 같아요.

2023-01-06 04:06 UTC, EuniceNam commented on GetARock/GetARock/Screen/GatheringInfo/GatheringInfoViewController.swift
> -import UIKit
p2; 이 파일에 추가 들여쓰기가 들어갔는데, 전체 선택하시고 ctrl + i 하시면 들여쓰기 맞춰집니다. 이 부분 수정하시면 수정한 라인 수도 줄어들 거에요.

2023-01-06 13:59 UTC, siro96-01 commented on GetARock/GetARock/Global/Resource/Storyboards/GatheringInfoPage.storyboard
> +                                                            <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" textAlignme
ㅋㅋㅋㅋㅋ.. 부끄럽네요..

2023-01-06 14:00 UTC, siro96-01 commented on GetARock/GetARock/Screen/GatheringInfo/GatheringInfoViewController.swift
> +            @IBOutlet weak var conditionView: UIView!
오...! 좋은 생각인거 같아요...! statusView로 바꾸도록 하겠습니다..!!

2023-01-06 14:01 UTC, siro96-01 commented on GetARock/GetARock/Global/Supports/Info.plist
> -					<string>Landing</string>
급하게 올리느라 꼼꼼하게 보지를 못했네요 ㅠㅠ

2023-01-06 14:24 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2023-01-06 14:44 UTC, siro96-01 commented on GetARock/GetARock/Screen/GatheringInfo/GatheringInfoViewController.swift
> +            @IBOutlet weak var conditionView: UIView!
0530edb

2023-01-06 15:21 UTC, EuniceNam approved these changes

2023-01-06 15:22 UTC, EuniceNam commented on GetARock/GetARock/Screen/GatheringInfo/GatheringInfoViewController.swift
> +            @IBOutlet weak var conditionView: UIView!
고생하셨습니다!

2023-01-08 08:08 UTC, GODNOEL approved these changes
핫픽스 어프루브 드립니다...!

2023-01-08 08:15 UTC, compuTasha approved these changes
확인했습니다! 빠른 픽스 감사합니다!!

2023-01-08 08:19 UTC, closed without merging