[Design] 모여락(밴드 이벤트) 추가 화면을 구현합니다.
DeveloperAcademy-POSTECH/MacC-GetARock pull request #61
Opened 2022-11-21 05:15 UTC by EuniceNam

## 관련 이슈
#36 

## 배경
모여락(밴드 이벤트)를 만들 때 유저가 정보를 입력하는 화면을 구현합니다. 

## 작업 내용
스토리보드만 사용했습니다.  
스토리보드의 라인 수가 많아 텍스트뷰의 플레이스홀더처럼 코드를 쓰는 것은 PR을 분리합니다. 
1. 네비게이션 컨트롤은 모여락 위치 선택 뷰로의 연결을 위해 먼저 추가했습니다.
2. 화면은 밴드소개가 길어질 것을 대비해 스크롤뷰를 사용했습니다. 
  - 키보드 영역까지 하면 스크롤뷰가 필요할 것 같습니다.
3. 색과 폰트는 장소와 저장 기능 구현 후 고치려고 합니다. 

## 테스트 방법
모달로 쓸 뷰라서 다른 뷰에서 연결해서 보면 좋습니다. 
테스트 시작용 스토리보드를 따로 만들어두고, 스토리보드 레퍼런스로 연결하면 편합니다. 

## 리뷰 노트
- 텍스트뷰 플레이스홀더, 위치 선택 뷰 연결과 키보드 관련 일부 설정은 다음 PR로 넘깁니다. 
- PR 사이즈와 관련해서 스토리보드의 코드 줄 수를 생각하는 게 어렵네요. 노하우 있으신 분 알려주시면 감사합니다. 

## 스크린샷
피그마 | 스크린샷 |
:----: | :----: |
<img width="300" alt="" src="https://user-images.githubusercontent.com/18394923/202927621-566dc7fb-0c88-4687-b84d-d2634918a0fb.png"> | <img width="300" alt="" src="https://user-images.githubusercontent.com/18394923/202970605-c85518d7-d51c-416c-92b2-b98e54675613.png"> |

2022-11-21 05:23 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2022-11-21 10:51 UTC, compuTasha commented
아닛 스크린샷에서 디자인이 더 아름다워졌는걸요..?? 너무 좋아요

2022-11-21 11:17 UTC, compuTasha requested changes
p2;

현재 `Scroll View`의 콘텐츠에 해당하는 `ScrollContentView` 의 좌우 constraint 가 없어서
`Scroll View`가 콘텐츠의 너비를 인식을 못하는 것 같아요!
  
<img width="462" alt="image" src="https://user-images.githubusercontent.com/51108729/203034483-e3aa5b98-74d3-4f1e-b91a-7755f2490165.png">  

`Scroll View`와 `ScrollContentView` 사이의 trailing/leading constraint 를 추가해주세용

---

그리고 이것과 별개로 Scroll View 에는 `Content Layout Guide`와 `Frame Layout Guide`, 
2개의 레이아웃 가이드가 있고
이를 잘 활용하면 스크롤 가능한 컨텐츠를 보다 효과적으로 제어할 수 있다고 합니다.

각자가 의미하는 바는 아래와 같습니다!
```
- Content Layout Guide: 들어오는 컨텐츠에 따라 레이아웃을 변경시켜줄게. 컨텐츠 크기를 나에게 알려 줘.
- Frame Layout Guide: 스크롤과 관계 없이 화면 안에 있어야 할 요소가 있어? 나에게 위치를 알려 줘.
```

여기서는 `ScrollContentView`의 width는 `Scroll View`의 `Frame Layout Guide`에 constraint를 설정하고, 
나머지 top, bottom, leading, trailing 은 `Scroll View`의 `Content Layout Guide`에 고정하는 게 적절해보여요!

자세한 설명은 [이 블로그](https://kyungmosung.github.io/2019/11/06/xcode-scrollview/) 참고해주세용

2022-11-21 15:32 UTC, skycat0212 commented
풀받고 conflict 해결해주세요 ㅠ

2022-11-21 15:34 UTC, skycat0212 commented on GetARock/GetARock/Screen/AddGathering/AddGatheringViewController.swift
> +//  AddGatheringViewController.swift
p1;
파일 이름 확인 부탁드려요~

2022-11-21 22:50 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2022-11-21 23:40 UTC, EuniceNam commented
반영했습니다. 8f22d8de9e4b769198ce89c4496c0e0de2b143d6

Xcode13의 인터페이스 빌더에서는 content와 frame을 꼭 따로 지정해야했던 것 같은데 Xcode14에서 그렇게 안 해도 되는 걸 보고 조사 없이 했었네요. frame을 나눠서 하니 frame의 bottom으로 키보드에 대한 것도 해결될 수 있을 것 같기도 하고, 더 정리되는 것 같아서 좋네요. 감사합니다. 


> p2;
> 
> 현재 `Scroll View`의 콘텐츠에 해당하는 `ScrollContentView` 의 좌우 constraint 가 없어서 `Scroll View`가 콘텐츠의 너비를 인식을 못하는 것 같아요!
> 
> <img alt="image" width="462" src="https://user-images.githubusercontent.com/51108729/203034483-e3aa5b98-74d3-4f1e-b91a-7755f2490165.png">
> 
> `Scroll View`와 `ScrollContentView` 사이의 trailing/leading constraint 를 추가해주세용
> 
> 그리고 이것과 별개로 Scroll View 에는 `Content Layout Guide`와 `Frame Layout Guide`, 2개의 레이아웃 가이드가 있고 이를 잘 활용하면 스크롤 가능한 컨텐츠를 보다 효과적으로 제어할 수 있다고 합니다.
> 
> 각자가 의미하는 바는 아래와 같습니다!
> 
> ```
> - Content Layout Guide: 들어오는 컨텐츠에 따라 레이아웃을 변경시켜줄게. 컨텐츠 크기를 나에게 알려 줘.
> - Frame Layout Guide: 스크롤과 관계 없이 화면 안에 있어야 할 요소가 있어? 나에게 위치를 알려 줘.
> ```
> 
> 여기서는 `ScrollContentView`의 width는 `Scroll View`의 `Frame Layout Guide`에 constraint를 설정하고, 나머지 top, bottom, leading, trailing 은 `Scroll View`의 `Content Layout Guide`에 고정하는 게 적절해보여요!
> 
> 자세한 설명은 [이 블로그](https://kyungmosung.github.io/2019/11/06/xcode-scrollview/) 참고해주세용

2022-11-21 23:41 UTC, EuniceNam commented
> 풀받고 conflict 해결해주세요 ㅠ

생각 못했는데 계속 고려해야할 사항이네요. 알려주셔서 감사합니다!

2022-11-21 23:41 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2022-11-21 23:43 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2022-11-21 23:51 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2022-11-22 00:24 UTC, EuniceNam commented on GetARock/GetARock/Global/Resource/Storyboards/AddGathering.storyboard
> +                                </subviews>
인터페이스 빌더에서의 컴포넌트화 방법을 아예 생각하지 않고 만든 것 같아 추후 알아볼게요. 좋은 코멘트 감사합니다!

2022-11-22 01:29 UTC, compuTasha approved these changes
수고하셨습니다! 🤩

2022-11-22 01:36 UTC, skycat0212 approved these changes
유니스~ 수고하셨습니다!

2022-11-22 01:57 UTC, merged