[Feat] 내모여락 화면에서 SegmentedControl 버튼을 누르면 해당하는 화면이 나타납니다.
DeveloperAcademy-POSTECH/MacC-GetARock pull request #92
Opened 2022-11-23 08:34 UTC by Somin-DS

## 관련 이슈
- close #86 

## 배경

내 모여락 화면에서 내가 만든 모여락/댓글 단 모여락 버튼을 누르면 각각 해당하는 화면이 보여집니다.

## 작업 내용

👉🏻 이전에 만들어놓은 ViewSwitchSegmentedControl 뷰와 GatheringCreatedViewController를 연결했습니다.

👉🏻 GatheringCreatedViewController안에 있는 테이블뷰를 내가 만든 모여락/댓글 단 모여락에서 공통적으로 쓰고 있고, 안에 데이터만 달라지기 때문에 버튼을 눌렀을 때 분기처리를 해서 해당하는 데이터를 불러오도록 구현했습니다.

👉🏻 현재 데이터상에서 내가 만든 모여락과 댓글 단 모여락을 가져오는데에 적절하지 않은 부분이 있어서 일단 분기처리만 해놓은 상태고, 추후 데이터 모델이 완성되면 그 때 알맞은 데이터를 넣어줄 예정입니다.

## 테스트 방법
`SceneDelegate` - ```func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) ``` 안에 아래 코드를 넣으면 시뮬레이터에서 확인하실 수 있습니다.

``` swift
   guard let windowScene = (scene as? UIWindowScene) else { return }
                    window = UIWindow(windowScene: windowScene)
                    window?.rootViewController = GatheringListViewController()
                    window?.makeKeyAndVisible()
    }
```
   

## 리뷰 노트

## 스크린샷
![Simulator Screen Recording - iPhone 14 Pro - 2022-11-23 at 17 31 51](https://user-images.githubusercontent.com/69718283/203501462-bab7cb1d-1be2-47ea-9cbe-1907f2687728.gif)

2022-11-23 14:19 UTC, skycat0212 commented on GetARock/GetARock/Global/UIComponent/ViewSwitchedSegmentedControl.swift
> +    weak var viewSwitchedSegmentedControldelegate: ViewSwitchedSegmentedControlDelegate?
p1;
camelCase 지켜주세용
+) 이 클래스에 대한 delegate로 클래스이름+delegate 형태다보니 그냥 delegate라는 네이밍만 해도 괜찮지 않을까합니다.

2022-11-23 14:22 UTC, skycat0212 commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +}
p2;
GatheringType이라고 하기에 모든 Gathering에 적용되는 내용이 아니라, 내 활동에 들어갈 Gathering에만 적용될 내용이므로 네이밍이 적합하지 않은 것 같아요.
RelatedGatheringType 등으로 네이밍을 바꿔보면 어떨까요?

2022-11-23 14:30 UTC, skycat0212 commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +
p5;
없어도 될 개행같아요😃😃😃

2022-11-23 14:31 UTC, skycat0212 commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +    private let gatheringListContentViewController: GatheringCreatedViewController = UIStoryboard(name: "GatheringView", bundle: nil).instantiateViewController(withIdentifier: GatheringCreatedViewCon
p5;
행이 조금 긴 것 같은데 개행을 섞어보면 어떨까요? 😀

2022-11-23 14:36 UTC, skycat0212 commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +    }
p2;
클린 코드에 따르면 추상화 수준이 높은 상위 함수가 먼저 정의되는게 가독성이 좋다고 합니다.
함수 순서를 바꿔주시면 위에서 아래로 읽으면서 코드 흐름을 보다 파악할 수 있을 것 같아요.

2022-11-23 15:23 UTC, Somin-DS commented on GetARock/GetARock/Global/UIComponent/ViewSwitchedSegmentedControl.swift
> +    weak var viewSwitchedSegmentedControldelegate: ViewSwitchedSegmentedControlDelegate?
이름이 너무 길게 지었더니 이런 일이 생기네요ㅠㅠ 수정했습니다! bfb05b4167c2396df8bff79068c464c5f0327483

2022-11-23 15:24 UTC, Somin-DS commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +}
@skycat0212 네이밍은 항상 어렵군요ㅠㅠ GatheringListType으로 변경해봤는데 어떠신가요? 50286919b16f9cd5d9fc60b4d3077287f6988104

2022-11-23 15:24 UTC, Somin-DS commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +
@skycat0212 감사합니다 바로 삭제했습니다! 2a59d1e69107eccb28e124068ae346be098e7a9c

2022-11-23 15:24 UTC, Somin-DS commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +    private let gatheringListContentViewController: GatheringCreatedViewController = UIStoryboard(name: "GatheringView", bundle: nil).instantiateViewController(withIdentifier: GatheringCreatedViewCon
@skycat0212 개행 넣어서 코드를 정리해봤는데 어느 부분에 개행을 하는게 적절한지 아직 어렵네요... 한번 더 확인해주시면 감사하겠습니다!! 2a59d1e69107eccb28e124068ae346be098e7a9c

2022-11-23 15:28 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2022-11-23 15:30 UTC, Somin-DS commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +    }
@skycat0212 오오오 스누피 감사합니다!! 오늘도 한수 배웠습니다!!!2a59d1e69107eccb28e124068ae346be098e7a9c

2022-11-23 16:59 UTC, skycat0212 commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +    GatheringCreatedViewController ?? GatheringCreatedViewController()
```suggestion
    private let segmentedControlButtons = ViewSwitchedSegmentedControl(
        buttonTitles: [
            GatheringListType.gatheringCreated.toKorean(),
            GatheringListType.gatheringJoined.toKorean()
        ]
    )
    private let gatheringListContentViewController = UIStoryboard(
        name: "GatheringView",
        bundle: nil
    ).instantiateViewController(
        withIdentifier: GatheringCreatedViewController.className
    ) as? GatheringCreatedViewController ?? GatheringCreatedViewController()
```
혹시 이건 어떨까요? 적당한 개행 어렵네요 ㅠㅠ

2022-11-23 16:59 UTC, skycat0212 commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +    }
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
커밋 번호 잘 알아갑니다

2022-11-23 17:13 UTC, skycat0212 commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +        ])
p5;
메서드들 사이에는 1줄씩 개행이 있어도 괜찮을 것 같아요😀

2022-11-23 17:47 UTC, Somin-DS commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +    }
@skycat0212 아니 이게 왜.......ㅎ............ㅠㅠㅠㅠㅠㅋㅋㅋㅋㅋㅋㅋㅋㅋ 커밋번호 다시 올립니다....❤️ 2a59d1e69107eccb28e124068ae346be098e7a9c

2022-11-24 07:54 UTC, unuhqueen approved these changes
머피 고생하셨습니당!

2022-11-24 07:54 UTC, unuhqueen commented on GetARock/GetARock/Screen/Gathering/GatheringCreatedViewController.swift
> +            return gathering.count > 2 ? gathering.count - 2 : gathering.count
q;
count에서 2를 뺀건 임시로 다른 view처럼 보이게 하기 위함일까요?

2022-11-24 07:54 UTC, unuhqueen commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +        view.backgroundColor = .modalBackgroundBlue
q;
저도 잘 모르는 부분이라 질문드려요! 이 두개의 view를 stack view가 아니라 autolayout으로 연결한 이유가 궁금합니당

2022-11-29 08:05 UTC, compuTasha reviewed
누피가 이미 리뷰를 꼼꼼히 해주셔서,,🥺
스윽 코멘트 덧붙이고 갑니다..

2022-11-30 02:38 UTC, Somin-DS commented on GetARock/GetARock/Screen/Gathering/GatheringCreatedViewController.swift
> +            return gathering.count > 2 ? gathering.count - 2 : gathering.count
@unuhqueen 네 맞아요! 일단 데이터가 똑같은 형태라서 다른화면이라고 보여주기위해 임시로 넣어놨습니다

2022-11-30 02:40 UTC, Somin-DS commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +        view.backgroundColor = .modalBackgroundBlue
@unuhqueen 이건 제 개인적인 습관? 같은것같아요 제가 아직 stack view를 autolayout보다 편하게 사용을 못하기도하고 일단 view가 단 2개뿐이라서 autolayout으로 충분할 것같아서 stack view에 안넣었습니다!

2022-12-01 02:06 UTC, skycat0212 commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +}
enum의 이름은 괜찮은 것 같은데, case 네이밍은 다시 생각해보면 좋을 것 같아요.
GatheringListType의 case이므로 case 네이밍에 gathering이 중복해서 들어가는 건 과한 것 같아보여요.
그리고, gatheringCreated  등의 네이밍은 '내가 만든 모여락'을 지칭하기에 어순도 적합하지 않은 것 같고, 내가 만든 모여락이라는 뉘앙스가 충분히 전달되지 않는 것 같습니다.

2022-12-01 23:32 UTC, siro96-01 commented on GetARock/GetARock/Screen/Gathering/GatheringCreatedViewController.swift
>          tableView.register(nibName, forCellReuseIdentifier: GatheringCell.className)
머피 좋은 코드들 잘 구경했습니다~! 
혹시 tableView.register 에는 .className 을 사용하셨는데, 
nibName에는 "GatheringCell" 로 적으신 이유가 있을까용?

2022-12-01 23:42 UTC, siro96-01 commented on GetARock/GetARock/Screen/Gathering/GatheringCreatedViewController.swift
> +    }
q;
이부분도 혹시 접근제어를 사용이 가능한가요?(잘 몰라서 질문...)
제가 봤을때는 이부분도 GatheringCreatedViewController에서만 사용되는 변수이기 때문에 private를 사용할 수 있지 않을까 싶어서 건의드려봅니다....ㅠ 아님말구...

2022-12-02 11:56 UTC, Somin-DS commented on GetARock/GetARock/Screen/Gathering/GatheringCreatedViewController.swift
>          tableView.register(nibName, forCellReuseIdentifier: GatheringCell.className)
nibNamed은 스토리보드 파일 이름이라서  "GatheringCell"로 적었어요! .className은 지금 ~~~ViewController로 되어있어서 identifier는 ViewController랑 통일시키기로 해서 그렇게 사용했구요! 하지만 "GatheringCell" 이렇게 바로 string으로 사용하기보단 확실히 다른 방식으로 하는게 안전성에 있어서 더 좋을 것 같네요! 감사합니다!

2022-12-02 11:56 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2022-12-02 12:02 UTC, Somin-DS commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +}
@skycat0212 이미 GatheringCreatedViewController가 만들어져 있어서 통일성을 위해 네이밍을 이렇게 했는데 스누피 의견도 동의해서 일단 계속 네이밍 생각해보겠습니다! 지금 당장 마땅한게 떠오르지가 않아서요ㅠ discussion에 올려보거나 다른 좋은 아이디어가 있는지도 한번 물어보겠습니다!

2022-12-02 12:03 UTC, Somin-DS commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +    GatheringCreatedViewController ?? GatheringCreatedViewController()
@skycat0212 제가 처음에 했던 개행보다 훨씬 가시성이 좋은 것 같아요! 수정했습니다 감사합니다! bd2b7fd5380d10d4cbb2f12213a5c4a755c4d76b

2022-12-02 12:11 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2022-12-02 16:13 UTC, skycat0212 commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +    GatheringCreatedViewController()
p5;
줄여도 되는 개행 아닐까요?
캐스팅 실패를 위한 디폴트 값과는 별개의 인스턴스 생성처럼 느껴지기도 하는 것 같아요

2022-12-02 16:16 UTC, skycat0212 commented on GetARock/GetARock/Screen/Gathering/GatheringCreatedViewController.swift
>          tableView.register(nibName, forCellReuseIdentifier: GatheringCell.className)
p5;
함수로 추상화 해보는 건 어떨까요?
아직 코드의 양은 많지 않지만, 코드들이 수행하고 있는 역할들이 달라서 분리해도 괜찮을 것 같아요.

2022-12-02 16:19 UTC, skycat0212 requested changes
전반적으로 네이밍의 어순이 어색한 것 같아요.
gatheringCreated
gatheringJoined
GatheringCreatedViewController
ViewSwitchedSegmentedControl
등이 자연스럽게 읽히지 않는 것 같습니다.

예를 들어, gatheringCreated 라면 나타내고자 하는 것이 '내가 만든 모여락'이므로 적어도 '만든 모여락'인 createdGathering 등의 방식으로 네이밍이 하는 것이 더 적합한 것 같습니다.
확인 부탁드려요!

2023-01-03 10:58 UTC, compuTasha commented
@skycat0212 @Somin-DS 
시간이 많이 지나서 다시 한번 리마인더 드립니당 확인 부탁드려요! 🫶

2023-01-06 07:52 UTC, skycat0212 commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +}
case 이름으로 `owned` 와 `joined`를 사용하는 것은 어떨까요?

2023-01-06 07:56 UTC, skycat0212 commented
여기 enum case 네이밍 변경 제안 드린부분과
https://github.com/DeveloperAcademy-POSTECH/MacC-GetARock/pull/92#discussion_r1063214055

https://github.com/DeveloperAcademy-POSTECH/MacC-GetARock/pull/92#pullrequestreview-1202746270 에서
ViewSwitchedSegmentedControl 네이밍 변경 요청 부분,

https://github.com/DeveloperAcademy-POSTECH/MacC-GetARock/pull/92#discussion_r1038302665
https://github.com/DeveloperAcademy-POSTECH/MacC-GetARock/pull/92#discussion_r1038304939
이 두 부분 확인 요청 드려요!

2023-01-07 05:28 UTC, Somin-DS commented on GetARock/GetARock/Screen/Gathering/GatheringCreatedViewController.swift
>          tableView.register(nibName, forCellReuseIdentifier: GatheringCell.className)
@skycat0212 혹시 정확히 어느 부분을 말씀하시는건지 알 수 있을까요?ㅜㅜ

2023-01-07 05:33 UTC, Somin-DS commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +}
@skycat0212 owned보다는 created가 좀더 직관적일 것 같은데 어떠신가요? createdGathering/joinedGathering으로 일단 수정했습니다! 58624205546e069fc6b07f1b0dc9681779eb3020

2023-01-07 05:35 UTC, Somin-DS commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +        ])
@skycat0212 감사합니다 반영했습니다! 741736aef9e879bb1544c05acc4c780e11767167

2023-01-07 05:36 UTC, Somin-DS commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +    GatheringCreatedViewController()
@skycat0212 수정과정에서 개행이 추가됐던 것 같습니다ㅠㅠ 다시 수정했습니다! 741736aef9e879bb1544c05acc4c780e11767167

2023-01-07 05:37 UTC, Somin-DS commented
@skycat0212 ViewSwitchedSegmentedControl -> SwitchingViewSegmentedControl로 수정해봤습니다! 나머지 부분은 수정사항 댓글에 남겨두었습니다! d2afd0bc3402bb2b19e40add35f1d3d2d629aa48

2023-01-07 05:40 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |

2023-01-08 07:29 UTC, skycat0212 commented on GetARock/GetARock/Screen/Gathering/GatheringListViewController.swift
> +}
개인적으로 owned가 created보다 주체를 명확히 느낄 수 있는 표현 같아서 owned를 제안드렸지만, 지금 변경된 내용도 괜찮은 것 같네요

2023-01-08 07:42 UTC, skycat0212 commented on GetARock/GetARock/Screen/Gathering/GatheringCreatedViewController.swift
>          tableView.register(nibName, forCellReuseIdentifier: GatheringCell.className)
viewDidLoad 안에서 실행되고 있는 위의 코드들이 viewDidLoad 함수 안에서 나열되어 있기에 각각 코드의 역할이 다르고 viewDidLoad의 맥락을 담지 못하는 것 같아요.
어떤 코드는 backgroundColor를 지정하고 있고, 어떤 코드는 nibName을 변화와 하고 있으며, 어떤 코드는 tableView에 해당 nib를 등록하고 있습니다.
사실 아직 코드 양이 많지 않아 그냥 진행할 수도 있지만, viewDidLoad에 바로 담기에는 각각의 코드의 역할이 다르지 않나 하는 생각이 들었습니다.

2023-01-08 07:44 UTC, skycat0212 approved these changes
머피 수고하셨습니다

2023-01-08 11:57 UTC, compuTasha approved these changes
머피 수고하셨습니다! 🥹
PR에 달린 스누피 리뷰 보고 저도 공부하고 갑니다..

2023-01-08 11:57 UTC, compuTasha commented on GetARock/GetARock/Screen/Gathering/GatheringCreatedViewController.swift
>          tableView.register(nibName, forCellReuseIdentifier: GatheringCell.className)
비슷한 이야기인 것 같아 다른 레포의 리뷰지만 [비비의 리뷰](https://github.com/DeveloperAcademy-POSTECH/MC3-Team13-Inception/pull/30#discussion_r926545240) 들고 왔습니다..!

2023-01-08 11:57 UTC, compuTasha commented on GetARock/GetARock/Screen/Gathering/GatheringCreatedViewController.swift
>          tableView.register(nibName, forCellReuseIdentifier: GatheringCell.className)
수정 전과 수정 후 코드 참고하시면 될 것 같아요!

2023-01-08 13:32 UTC, merged

2023-01-08 13:39 UTC, skycat0212 commented
## All File Checked ✅
| ✅     | SwiftBuilder Success!!!!     |
|---    |----------------------------------------------    |